[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "txt"]
roots = [".marksman.toml"]
language-servers = [ "ltex-ls", "marksman" ]
indent = { tab-width = 2, unit = "  " }
