#!/usr/bin/env zsh

TMPBG=/tmp/screen.png
LOCK=${0:a:h}/lock.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

sleep 0.1s
ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -i $LOCK -i $LOCK -filter_complex "boxblur=5:1,overlay=0:0,overlay=1920:0,overlay=3840:0" -vframes 1 $TMPBG
i3lock -i $TMPBG
rm $TMPBG
