#!/bin/zsh

# Notification
# TODO: dunst?
#/usr/libexec/xfce4/notifyd/xfce4-notifyd &

# Transparency
picom --fading --inactive-opacity=1 &

# Sound notification and applet
volumeicon &

# Clipboard manager
clipit &

# Package manager tray icon
pamac-tray &

# Bluetooth
blueman-applet &

# Authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Keybase
# TODO: enable a service? start application instead?
#keybase service &

# TODO: still necessary?
#dbus-update-activation-environment --systemd DISPLAY
#eval $(/usr/bin/gnome-keyring-daemon --start)
#export SSH_AUTH_SOCK

# TODO: fix_xcursor?
# TODO: ff-theme-util?
# TODO: start_conky_maia?
# TODO: sbxkb?
# TODO: xautolock?
# TODO: pulseaudio
# TODO: pa-applet?

# Empty trash
gio trash --empty

# Power manager + battery and light tray
# Tray icon is enabled in `xfce4-power-manager-settings`
xfce4-power-manager &

# Delayed startup
(
    sleep 10

    # title watcher must be started after i3blocks to avoid some issues
    ~/.local/wm/i3/window-title-watcher &

    fcitx &

    # make screen HOT
    redshift-gtk -l 45.5:-73.5 & # Canada, Montreal

    # LXDE network applet
    nm-applet &

    # Startup todo / calendar display using calcurse
    notify-send -u normal --icon=x-office-calendar "$(calcurse --query --days 5 --output-datefmt '%y/%m/%d (%A)')"

    # Background
    # TODO: artwork-i3?
    # TODO: nitrogen? https://wiki.archlinux.org/title/nitrogen
    #$HOME/.local/wm/i3/set_random_bg &
) &

# repeater
(
    while true; do
        sleep 2760 # 46 minutes
        $HOME/.local/wm/i3/warn_next_appointement.nu
    done
) &
