#!/bin/zsh

# Notification
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Transparency
picom &

# Sound notification
volnoti &

# Clipboard manager
parcellite &

# Background
$HOME/.local/wm/i3/set_random_bg &

# Authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

if [[ -v IS_WORKSTATION ]]; then
    firefox &
    emacs &
    alacritty --class "utility-term,utility-term" --working-directory ~/den-test/ &
else
    thunderbird &
fi

# delayed startup
(
    sleep 5

    fcitx &

    if [[ -v IS_WORKSTATION ]]; then
        # multi monitors
        xrandr --output DP-3 --auto --pos 0x0               --output DP-6 --auto --pos 0x0 \
               --output DP-1 --primary --auto --pos 1920x0  --output DP-4 --primary --auto --pos 1920x0 \
               --output DP-2 --auto --pos 3840x0            --output DP-5 --auto --pos 3840x0

        i3-msg \[class="firefox"\] move window to workspace 5
        i3-msg \[class="Emacs"\] move window to workspace 3
        i3-msg \[class="utility-term"\] move window to workspace 1

        # Telegram
        telegram-desktop -startintray &
    else
        # make screen HOT
        redshift-gtk -l 45.5:-73.5 & # Canada, Montreal

        # multi monitors quick fix
        intel-virtual-output && xrandr --output eDP1 --auto --output VIRTUAL1 --auto --right-of eDP1 &

        # todos notif (FIXME: remove?)
        ~/scripts/show-next-todos.py &

        # Telegram
        telegram-desktop -startintray &

        # LXDE network applet
        nm-applet &

        i3-msg \[class="Thunderbird"\] move window to workspace 10
    fi
) &
