#!/bin/bash
i3-msg layout toggle split
i3-msg split h

#anki &
~/scripts/virtualanki &
sleep 7
disown

i3-msg layout stacking
i3-msg focus parent
i3-msg split h

firefox --no-remote -p japanese &
sleep 1
disown

i3-msg split v

thunar ~/Desktop/訓練写真/ ~/DownloadsLight/ &
sleep 1
disown

i3-msg layout stacking

