#!/bin/bash
scrot -s --overwrite /tmp/tmpscrot_ocr.png
tesseract /tmp/tmpscrot_ocr.png /tmp/ocr_out -l jpn
env cat /tmp/ocr_out.txt | sed -r 's/ //g' | xsel --input --clipboard
rm /tmp/tmpscrot_ocr.png

