#!/bin/bash

if ! playerctl status > /dev/null; then
    exit 0
fi

DEFAULT_COLOR=${DEFAULT_COLOR:-"#ffffff"}
MUTED_COLOR=${MUTED_COLOR:-"#a0a0a0"}

case "$BLOCK_BUTTON" in
    1) playerctl next ;;
    2) playerctl play-pause ;;
    3) playerctl previous ;;
    4) playerctl volume 0.1+ ;;
    5) playerctl volume 0.1- ;;
esac

volume_percent=$(echo "$(playerctl volume)*100" | bc | cut -c -5)
echo "$(playerctl metadata xesam:url | sed -e 's/.*\///' -e 's/....$//' | sed "s@+@ @g;s@%@\\\\x@g" | xargs -0 printf "%b") ($volume_percent%)"

if [[ "$(playerctl status)" =~ "Playing" ]]; then
    COLOR=$DEFAULT_COLOR
else
    COLOR=$MUTED_COLOR
fi
echo ""
echo "$COLOR"

