#!/bin/zsh

HOST=google.fr

rtt=$(ping $HOST -c 1 | sed -rn 's/.*time=([0-9]{1,})\.?[0-9]{0,} ms.*/\1/p')
char=

if [ "$rtt" -lt 50 ]; then
    icon="%{F#3cb703}${char}%{F-}"
elif [ "$rtt" -lt 150 ]; then
    icon="%{F#f9dd04}${char}%{F-}"
else
    icon="%{F#d60606}${char}%{F-}"
fi

echo "$icon $rtt ms"
