#!/bin/sh

player_status=$(playerctl status 2> /dev/null)

if [ "$player_status" = "Playing" ]; then
    echo -e "%{u#08ff00}%{T5}  %{T-} $(playerctl metadata artist) - $(playerctl metadata title)%{u-}"
elif [ "$player_status" = "Paused" ]; then
    echo -e "%{u#ff7200}%{T5}  %{T-} $(playerctl metadata artist) - $(playerctl metadata title)%{u-}"
else
    echo ""
fi
