#!/bin/zsh

updates_arch=$(checkupdates | wc -l)

if ! updates_aur=$(trizen -Su --aur --quiet | wc -l); then
    updates_aur=0
fi

if [[ "$updates_arch" -gt 0 || "$updates_aur" -gt 0 ]]; then
    echo "%{u#ff0010}$updates_arch %{F#5b5b5b}%{F-} $updates_aur%{u-}"
else
    echo ""
fi
