[language-server.efm]
command = "efm-langserver"

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "efm", only-features = ["format", "diagnostics"] },
]

[[language]]
name = "svelte"
auto-format = true
language-servers = [
  { name = "svelteserver", except-features = ["format"] },
  { name = "efm", only-features = ["format", "diagnostics"] },
]

[[language]]
name = "markdown"
language-servers = [ "ltex-ls", "marksman" ]
